---
# handlers file for qwen_model
- name: Restart Ollama
  ansible.builtin.systemd:
    name: ollama
    state: restarted
    daemon_reload: true

- name: reload ufw
  community.general.ufw:
    state: reloaded

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true