---
- name: Check if Ollama is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/ollama
  register: ollama_binary

- name: Install Ollama
  ansible.builtin.shell: "curl -fsSL https://ollama.com/install.sh | sh"
  when: not ollama_binary.stat.exists
  changed_when: ollama_binary.stat.exists == false # Only report change if it was actually installed

- name: Deploy Ollama systemd service
  ansible.builtin.template:
    src: ollama.service.j2
    dest: /etc/systemd/system/ollama.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Restart Ollama

- name: Ensure Ollama service is started and enabled
  ansible.builtin.systemd:
    name: ollama
    state: started
    enabled: true
    daemon_reload: true

- name: Pull the Qwen model
  ansible.builtin.command: "ollama pull {{ qwen_model_name }}"
  args:
    creates: /usr/share/ollama/.ollama/models/manifests/registry.ollama.ai/library/{{ qwen_model_name | replace(':', '/') }}
  changed_when: true # Always report as changed as the pull command can update the model

- name: Allow traffic to Qwen model with ufw
  community.general.ufw:
    rule: allow
    from: "{{ internal_network_subnet }}"
    to_port: "{{ qwen_model_port }}"
    proto: tcp
  notify: reload ufw
