---
- name: Install prerequisites for OpenResty
  become: true
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - crowdsec
      - gettext-base
    state: present

- name: Import OpenResty GPG key
  become: true
  ansible.builtin.get_url:
    url: https://openresty.org/package/pubkey.gpg
    dest: /etc/apt/trusted.gpg.d/openresty.asc
    mode: '0644'
    force: true

- name: Add OpenResty repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/openresty.asc] http://openresty.org/package/ubuntu {{ ansible_lsb.codename }} main"
    state: present
    update_cache: true

- name: Install OpenResty
  become: true
  ansible.builtin.package:
    name: openresty
    state: present

- name: Ensure OpenResty log directory exists
  become: true
  ansible.builtin.file:
    path: /var/log/openresty
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create conf.d directory
  become: true
  ansible.builtin.file:
    path: /usr/local/openresty/nginx/conf/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Template nginx.conf (global OpenResty config)
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /usr/local/openresty/nginx/conf/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart OpenResty

- name: Add Certbot server block to OpenResty configuration
  become: true
  ansible.builtin.template:
    src: certbot.conf.j2
    dest: /usr/local/openresty/nginx/conf/conf.d/certbot.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart OpenResty

- name: Download CrowdSec repository setup script
  become: true
  ansible.builtin.get_url:
    url: https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh?any=true
    dest: /tmp/crowdsec-repo-setup.sh
    mode: '0755'

- name: Execute CrowdSec repository setup script
  become: true
  ansible.builtin.command:
    cmd: /tmp/crowdsec-repo-setup.sh
    creates: /etc/apt/sources.list.d/crowdsec_crowdsec.list

- name: Install CrowdSec OpenResty bouncer
  become: true
  ansible.builtin.package:
    name: crowdsec-openresty-bouncer
    state: present
  notify: Restart OpenResty
